version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: codechallenge_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  hansecom-codechallenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hansecom-codechallenge
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SERVER_SERVLET_CONTEXT_PATH: /hansecom-codechallenge
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/codechallenge_db
    volumes:
      - ./build/libs:/app/build/libs

    command: java -jar /hansecom-codechallenge.war

volumes:
  postgres_data: